import { useState } from 'react';
import JSZip from 'jszip';
import { Shield, CheckCircle, Lock, FileJson, FileText, Hash, Clock, Package } from 'lucide-react';
import { useContractStore } from '../../store/contract-store';
import { Button, Checkbox, Card } from '../ui';

export function FinalizationScreen() {
  const {
    session,
    updateFinalization,
    finalizeContract,
    resetSession,
    goToStage,
  } = useContractStore();

  const { framing, inputs, outputs, policies, rules, simulation, finalization } = session;
  const [showCanonicalPreview, setShowCanonicalPreview] = useState(false);

  const handleFinalize = () => {
    if (finalization.approval_confirmed) {
      finalizeContract();
    }
  };

  const canonicalContract = {
    framing: {
      decision_name: framing.decision_name,
      decision_purpose: framing.decision_purpose,
      authority_type: framing.authority_type,
      permitted_actions: framing.permitted_actions,
      prohibited_actions: framing.prohibited_actions,
      escalation_requirement: framing.escalation_requirement,
    },
    inputs: {
      inputs: inputs.inputs.map((i) => ({
        name: i.name,
        type: i.type,
        required: i.required,
        missing_behavior: i.missing_behavior,
      })),
    },
    outputs: {
      outputs: outputs.outputs.map((o) => ({
        code: o.code,
        category: o.category,
        requires_reason_code: o.requires_reason_code,
      })),
      refusal_requirement: outputs.refusal_requirement,
    },
    policies: {
      policies: policies.policies.map((p) => ({
        policy_id: p.policy_id,
        statement: p.statement,
        constraint_type: p.constraint_type,
        condition: p.condition,
        violation_outcome: p.violation_outcome,
        reason_code: p.reason_code,
      })),
    },
    rules: {
      rules: rules.rules.map((r) => ({
        rule_id: r.rule_id,
        condition: r.condition,
        output: r.output,
        reason_code: r.reason_code,
      })),
    },
  };

  const canonicalJson = JSON.stringify(canonicalContract, null, 2);

  const refusalOutputs = outputs.outputs.filter((o) => o.category === 'REFUSAL');
  const hasRefusalCase = simulation.cases.some((c) => 
    refusalOutputs.some((ro) => ro.code === c.expected_output)
  );

  const handleDownload = (format: 'json' | 'md') => {
    const content = format === 'json' 
      ? canonicalJson 
      : generateMarkdown();
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${framing.decision_name.toLowerCase().replace(/\s+/g, '_')}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const generateMarkdown = () => {
    return `# Decision Contract: ${framing.decision_name}

## Purpose
${framing.decision_purpose}

## Authority Type
${framing.authority_type}

## Inputs
${inputs.inputs.map((i) => `- **${i.name}** (${i.type}) - ${i.required ? 'Required' : 'Optional'}`).join('\n')}

## Outputs
${outputs.outputs.map((o) => `- **${o.code}** (${o.category})`).join('\n')}

## Policies
${policies.policies.map((p) => `- **${p.policy_id}**: ${p.statement}`).join('\n')}

## Rules
${rules.rules.map((r) => `- **${r.rule_id}** → ${r.output}`).join('\n')}

## Simulation Results
- Total Cases: ${simulation.cases.length}
- All Passed: ${simulation.all_cases_passed ? 'Yes' : 'No'}

---
Generated by DCG Studio v1.0.0
`;
  };

  const generateSimulationTrace = () => {
    return JSON.stringify({
      cases: simulation.cases.map((c) => ({
        case_id: c.case_id,
        inputs: c.inputs,
        expected_output: c.expected_output,
        expected_reason_code: c.expected_reason_code,
        actual_output: c.actual_output,
        actual_reason_code: c.actual_reason_code,
        case_type: c.case_type,
        assertion_passed: c.assertion_passed,
        trace: c.trace,
      })),
      all_cases_passed: simulation.all_cases_passed,
      proof_confirmed: simulation.proof_confirmed,
    }, null, 2);
  };

  const handleExportBundle = async () => {
    if (!finalization.result) return;

    const zip = new JSZip();
    const decisionName = framing.decision_name.toLowerCase().replace(/\s+/g, '_');
    const version = finalization.result.audit_metadata.version;

    // contract.canonical.json - the hashed payload
    zip.file('contract.canonical.json', canonicalJson);

    // contract.hash - just the hash string
    zip.file('contract.hash', finalization.result.hash);

    // contract.md - human-readable documentation
    zip.file('contract.md', generateMarkdown());

    // simulation.trace.json - full simulation results
    zip.file('simulation.trace.json', generateSimulationTrace());

    // metadata.json - audit metadata (includes generated_at, outside hash)
    zip.file('metadata.json', JSON.stringify(finalization.result.audit_metadata, null, 2));

    // Generate and download
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `decision-contract_${decisionName}_v${version}.zip`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (finalization.is_finalized && finalization.result) {
    return (
      <div className="space-y-6">
        <div className="border-b border-slate-200 pb-4">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-8 h-8 text-green-600" />
            <div>
              <h1 className="text-2xl font-bold text-green-800">Contract Finalized</h1>
              <p className="mt-1 text-slate-600">
                This decision contract has been approved and is now immutable.
              </p>
            </div>
          </div>
        </div>

        <div className="p-6 bg-green-50 border border-green-200 rounded-lg">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-sm text-green-600">Contract ID</p>
              <p className="font-mono font-bold text-green-800">{finalization.result.contract_id}</p>
            </div>
            <div>
              <p className="text-sm text-green-600">Hash</p>
              <p className="font-mono text-sm text-green-800 break-all">{finalization.result.hash}</p>
            </div>
            <div>
              <p className="text-sm text-green-600">Finalized At</p>
              <p className="text-green-800">{new Date(finalization.result.hash_timestamp).toLocaleString()}</p>
            </div>
            <div>
              <p className="text-sm text-green-600">Canonical Size</p>
              <p className="text-green-800">{finalization.result.canonical_byte_length} bytes</p>
            </div>
          </div>
        </div>

        <Card title="Export Artifacts" description="Download the finalized contract in various formats.">
          <div className="space-y-4">
            <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
              <Button onClick={handleExportBundle} className="w-full justify-center">
                <Package className="w-4 h-4 mr-2" />
                Download Complete Bundle (.zip)
              </Button>
              <p className="text-xs text-blue-600 mt-2 text-center">
                Includes: contract.canonical.json, contract.hash, contract.md, simulation.trace.json, metadata.json
              </p>
            </div>
            <div className="flex gap-4">
              <Button variant="secondary" onClick={() => handleDownload('json')}>
                <FileJson className="w-4 h-4 mr-2" />
                JSON Only
              </Button>
              <Button variant="secondary" onClick={() => handleDownload('md')}>
                <FileText className="w-4 h-4 mr-2" />
                Markdown Only
              </Button>
            </div>
          </div>
        </Card>

        <div className="p-4 bg-slate-100 border border-slate-300 rounded-lg">
          <div className="flex items-center gap-2 text-slate-600">
            <Lock className="w-5 h-5" />
            <p className="text-sm">
              This contract is now immutable. No edits, no silent mutation, no unlock.
            </p>
          </div>
        </div>

        <div className="pt-4 border-t border-slate-200">
          <Button onClick={resetSession}>
            Start New Contract
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="border-b border-slate-200 pb-4">
        <div className="flex items-center gap-3">
          <Shield className="w-6 h-6 text-emerald-600" />
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Finalization</h1>
            <p className="mt-1 text-slate-600">
              Approve this decision contract as a governed artifact. Once finalized, no further mutation is allowed.
            </p>
          </div>
        </div>
      </div>

      <Card title="Contract Summary" description="Governance overview of the decision contract.">
        <div className="grid grid-cols-2 gap-4">
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Contract Name</p>
            <p className="font-medium text-slate-800">{framing.decision_name || '(Not set)'}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Authority Type</p>
            <p className="font-medium text-slate-800">{framing.authority_type || '(Not set)'}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Total Inputs</p>
            <p className="font-medium text-slate-800">{inputs.inputs.length}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Total Outputs</p>
            <p className="font-medium text-slate-800">{outputs.outputs.length}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Total Policies</p>
            <p className="font-medium text-slate-800">{policies.policies.length}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Total Rules</p>
            <p className="font-medium text-slate-800">{rules.rules.length}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Simulation Cases</p>
            <p className="font-medium text-slate-800">{simulation.cases.length}</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg">
            <p className="text-sm text-slate-500">Refusal Proven</p>
            <p className={`font-medium ${hasRefusalCase ? 'text-green-600' : 'text-red-600'}`}>
              {hasRefusalCase ? 'Yes' : 'No'}
            </p>
          </div>
        </div>
      </Card>

      <Card title="Canonical Contract Preview" description="Read-only preview of the canonical JSON that will be hashed.">
        <div className="space-y-3">
          <Button 
            variant="secondary" 
            onClick={() => setShowCanonicalPreview(!showCanonicalPreview)}
          >
            {showCanonicalPreview ? 'Hide Preview' : 'Show Preview'}
          </Button>
          {showCanonicalPreview && (
            <pre className="p-4 bg-slate-900 text-slate-100 rounded-lg overflow-auto max-h-96 text-xs">
              {canonicalJson}
            </pre>
          )}
          <p className="text-sm text-slate-500 italic">
            This preview is the contract. No edits allowed.
          </p>
        </div>
      </Card>

      <Card title="Hash & Integrity Proof" description="Cryptographic identity of the contract.">
        <div className="space-y-3">
          <div className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg">
            <Hash className="w-5 h-5 text-slate-400" />
            <div>
              <p className="text-sm text-slate-500">Hash Algorithm</p>
              <p className="font-mono text-slate-800">SHA-256</p>
            </div>
          </div>
          <div className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg">
            <Clock className="w-5 h-5 text-slate-400" />
            <div>
              <p className="text-sm text-slate-500">Canonical Byte Length</p>
              <p className="font-mono text-slate-800">{new TextEncoder().encode(canonicalJson).length} bytes</p>
            </div>
          </div>
          <p className="text-sm text-slate-500">
            The hash will be computed upon finalization and will serve as the permanent reference.
          </p>
        </div>
      </Card>

      <Card title="Export & Distribution" description="Available export formats after finalization.">
        <div className="grid grid-cols-3 gap-4">
          <div className="p-3 bg-slate-50 rounded-lg text-center">
            <FileJson className="w-6 h-6 mx-auto text-blue-500 mb-2" />
            <p className="text-sm font-medium">Canonical JSON</p>
            <p className="text-xs text-slate-500">Runtime enforcement</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg text-center">
            <FileText className="w-6 h-6 mx-auto text-purple-500 mb-2" />
            <p className="text-sm font-medium">PDF</p>
            <p className="text-xs text-slate-500">Governance & legal</p>
          </div>
          <div className="p-3 bg-slate-50 rounded-lg text-center">
            <FileText className="w-6 h-6 mx-auto text-green-500 mb-2" />
            <p className="text-sm font-medium">Markdown</p>
            <p className="text-xs text-slate-500">Documentation</p>
          </div>
        </div>
      </Card>

      <Card title="Governance Approval" description="This is a governance attestation, not a UX confirmation.">
        <div className="space-y-4">
          <Checkbox
            label="I approve this decision contract as the authoritative definition of what this system may decide"
            description="I understand that this artifact will be immutable and auditable. Once finalized, no further mutation is allowed."
            checked={finalization.approval_confirmed}
            onChange={(checked) => updateFinalization({ approval_confirmed: checked })}
          />
          
          {!simulation.proof_confirmed && (
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg">
              <p className="text-sm text-amber-700">
                Simulation proof must be confirmed before finalization.
              </p>
            </div>
          )}
        </div>
      </Card>

      <div className="flex items-center justify-between pt-4 border-t border-slate-200">
        <Button variant="ghost" onClick={() => goToStage('SIMULATION_FINALIZATION')}>
          ← Back to Simulation
        </Button>
        <Button
          onClick={handleFinalize}
          disabled={!finalization.approval_confirmed || !simulation.proof_confirmed || !simulation.all_cases_passed}
        >
          <Shield className="w-4 h-4 mr-2" />
          Finalize Contract
        </Button>
      </div>
    </div>
  );
}
