/**
 * Meta DDR Global Invariants
 * Frozen for MVP - v1.0
 */

export const INVARIANTS = {
  NO_AMBIGUITY_PERSISTS: 'NO_AMBIGUITY_PERSISTS',
  AUTHORITY_NEVER_FLOWS_UPWARD: 'AUTHORITY_NEVER_FLOWS_UPWARD',
  ALL_BEHAVIOR_DECLARED: 'ALL_BEHAVIOR_DECLARED',
  NO_IMPLICIT_DEFAULTS: 'NO_IMPLICIT_DEFAULTS',
  REFUSAL_IS_MANDATORY: 'REFUSAL_IS_MANDATORY',
  ALL_PATHS_TERMINATE: 'ALL_PATHS_TERMINATE',
  ONLY_DECLARED_INPUTS: 'ONLY_DECLARED_INPUTS',
  OUTPUTS_ARE_FINITE: 'OUTPUTS_ARE_FINITE',
  POLICIES_RESTRICT_NOT_GENERATE: 'POLICIES_RESTRICT_NOT_GENERATE',
  DETERMINISM_REQUIRED: 'DETERMINISM_REQUIRED',
  REPRODUCIBILITY_REQUIRED: 'REPRODUCIBILITY_REQUIRED',
} as const;

export type Invariant = (typeof INVARIANTS)[keyof typeof INVARIANTS];
